### ISSUE TITLE
mvn package

### ISSUE THREAD

**Issue by arora-manish** [redislabs-training/ru102j#46]
> mvn package
[INFO] Scanning for projects...
[WARNING] The project com.redislabs.university:redisolar:jar:1.0 uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO]
[INFO] -----------------< com.redislabs.university:redisolar >-----------------
[INFO] Building redisolar 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.sun.xml.bind:jaxb-core:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.sun.xml.bind:jaxb-impl:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- properties-maven-plugin:1.0.0:read-project-properties (default) @ redisolar ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ redisolar ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 55 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ redisolar ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ redisolar ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ redisolar ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ redisolar ---
[INFO] Surefire report directory: /Users/manisharora/work2/github/ru102j/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.redislabs.university.RU102J.resources.MeterReadingResourceTest
23:09:38.317 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
23:09:38.319 [main] INFO org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.4.2.Final
23:09:38.334 [main] DEBUG org.hibernate.validator.internal.engine.resolver.DefaultTraversableResolver - Cannot find javax.persistence.Persistence on classpath. Assuming non JPA 2 environment. All properties will per default be traversable.
23:09:38.337 [main] DEBUG org.hibernate.validator.internal.engine.ConfigurationImpl - Setting custom ParameterNameProvider of type io.dropwizard.jersey.validation.JerseyParameterNameProvider
23:09:38.338 [main] DEBUG org.hibernate.validator.internal.xml.ValidationXmlParser - Trying to load META-INF/validation.xml for XML based Validator configuration.
23:09:38.339 [main] DEBUG org.hibernate.validator.internal.xml.ResourceLoaderHelper - Trying to load META-INF/validation.xml via TCCL
23:09:38.340 [main] DEBUG org.hibernate.validator.internal.xml.ResourceLoaderHelper - Trying to load META-INF/validation.xml via Hibernate Validator's class loader
23:09:38.340 [main] DEBUG org.hibernate.validator.internal.xml.ValidationXmlParser - No META-INF/validation.xml found. Using annotation based configuration only.
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.883 sec
Running com.redislabs.university.RU102J.dao.SiteStatsDaoRedisImplTest
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.173 sec <<< FAILURE!
findById(com.redislabs.university.RU102J.dao.SiteStatsDaoRedisImplTest)  Time elapsed: 0.037 sec  <<< ERROR!
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:234)

....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.722 s
[INFO] Finished at: 2023-10-26T22:56:20-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project redisolar: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/manisharora/work2/github/ru102j/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by arora-manish** [comment]
Please note this problem doesn't appear - if redis is running in the background. Following instructions on docker-compose up -d ... docker-compose down, the next step i noticed was to run mvn package. Only after re-reading verbiage, it became clear to me, we need redis running in the background to proceed.
